version: '3'

networks:
  monitoring:
    external: true
    name: monitoring

volumes:
  es_data:
    driver: local
  kibana_data:
    driver: local

services:
  # Access api endpoint at http://localhost:9200
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - 9200:9200
    networks:
      - monitoring
    volumes:
      - /data/es_data:/usr/share/elasticsearch/data
    mem_limit: 2g
    environment:
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=65%
      - cluster.routing.allocation.disk.watermark.high=70%
      - xpack.security.enabled=false
      - xpack.security.audit.enabled=true
      - xpack.ml.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_HEAP_SIZE=700m"
      - "ES_JAVA_OPTS=-Xms1500m -Xmx1500m"
    restart: unless-stopped

  # Access Kibana at http://localhost:5601
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - 5601:5601
    networks:
      - monitoring
    volumes:
      - /data/kibana_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    restart: unless-stopped

  # RSS extractor
  xcontest-rss-extractor:
    image: fahy.xyz/xcontest-rss-extractor:v1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - RUN_INTERVAL_MINUTES=60
      - PORT=9095
    ports:
      - 9095:9095
    networks:
      - monitoring
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/extra-labels=app:xcontest"
    depends_on:
      - elasticsearch
    restart: unless-stopped
