version: '3'

networks:
  monitoring:
    external: true
    name: monitoring

volumes:
  es_data:
    driver: local
  kibana_data:
    driver: local
  stats_data:
    driver: local

services:
  # Access api endpoint at http://localhost:9200
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    ports:
      - 9200:9200
    networks:
      - monitoring
    volumes:
      - /data/es_data:/usr/share/elasticsearch/data
    mem_limit: 2g
    environment:
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=65%
      - cluster.routing.allocation.disk.watermark.high=70%
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=true
      - xpack.security.audit.enabled=true
      - xpack.ml.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_HEAP_SIZE=700m"
      - "ES_JAVA_OPTS=-Xms1500m -Xmx1500m"
    restart: unless-stopped

  # Access Kibana at http://localhost:5601
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.0.0
    ports:
      - 5601:5601
    networks:
      - monitoring
    volumes:
      - /data/kibana_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    restart: unless-stopped

  # RSS extractor
  xcontest-rss-extractor:
    image: fahy.xyz/xcontest-rss-extractor:v1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - RUN_INTERVAL_MINUTES=2
      - LOG_LEVEL=info
      - PORT=9095
    ports:
      - 9095:9095
    networks:
      - monitoring
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/extra-labels=app:xcontest-rss"
    depends_on:
      - elasticsearch
    restart: unless-stopped

  # Archive extractor
  xcontest-arch-extractor:
    image: fahy.xyz/xcontest-arch-extractor:v1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - LOG_LEVEL=debug
      - PORT=9096
      - URL=https://www.xcontest.org/2021/world/en/flights/#flights[start]=
      - START_FLIGHT_NUMBER=0
    ports:
      - 9096:9096
    networks:
      - monitoring
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=9096"
      - "prometheus.io/extra-labels=app:xcontest-arch"
    depends_on:
      - elasticsearch
    restart: "no"

  # Weekly stats
  weekly-stats:
    image: fahy.xyz/xcontest-weekly-stats:v1
    environment:
      - ES_CLUSTER_URL=http://elasticsearch:9200
    networks:
      - monitoring
    volumes:
      - /data/stats_data:/output/
