{
 "title": "Arch-Extractor",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "HTTP requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(xcontest_archextractor_http_requests_total[5m])  "
    }
   ]
  },
  {
   "title": "Total number of runs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "xcontest_archextractor_runs_total"
    }
   ]
  },
  {
   "title": "Total number of documents processed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "xcontest_archextractor_documents_total"
    }
   ]
  },
  {
   "title": "Documents processed rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(xcontest_archextractor_documents_total[5m])"
    }
   ]
  },
  {
   "title": "Duplicates rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(xcontest_archextractor_duplicates_total[5m])"
    }
   ]
  },
  {
   "title": "Number of errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "xcontest_archextractor_errors_total"
    }
   ]
  }
 ]
}