{
 "title": "Arch-Extractor by year",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "year", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  {
   "title": "HTTP requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(xcontest_archextractor_http_requests_total{app=\"$year\"}[5m])  ",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Total number of runs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "xcontest_archextractor_runs_total{app=\"$year\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Total number of documents processed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "xcontest_archextractor_documents_total{app=\"$year\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Documents processed rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(xcontest_archextractor_documents_total{app=\"$year\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Duplicates rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(xcontest_archextractor_duplicates_total{app=\"$year\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Number of errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "xcontest_archextractor_errors_total{app=\"$year\"}",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}