{
 "title": "RSS-Extractor",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(xcontest_rssextractor_runs_total[1m])"
    }
   ]
  },
  {
   "title": "Documents processed rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(xcontest_rssextractor_documents_total[5m])",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Duplicates rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(xcontest_rssextractor_duplicates_total[5m])",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Number of documents processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xcontest_rssextractor_documents_total"
    }
   ]
  },
  {
   "title": "Number of runs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xcontest_rssextractor_runs_total"
    }
   ]
  },
  {
   "title": "HTTP requests rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(xcontest_rssextractor_http_requests_total[5m])  ",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Errors rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(xcontest_rssextractor_errors_total[5m])",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Number of errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xcontest_rssextractor_errors_total"
    }
   ]
  }
 ]
}